### ISSUE TITLE
unable to Optionally enrich with sentiment information

### ISSUE THREAD

**Issue by waleyson** [watson-developer-cloud/assistant-dialog-flow-analysis#19] opened 2020-08-13 19:50 UTC
Please I am a newbie with a run notebook, I just picked up code to run run through the analysis for watson assistant,
I am unable to run the sentiment analysis part of the notebook
please see error below
TypeError                                 Traceback (most recent call last)
<ipython-input-45-870a0ff8a2d7> in <module>
----> 1 df_logs_to_analyze = sentiment_analysis.add_sentiment_columns(df_logs_to_analyze)
      2 #create insights, and highlights annotation for the transcript visualization
      3 NEGATIVE_SENTIMENT_THRESHOLD=-0.15
      4 df_logs_to_analyze["insights_tags"] = df_logs_to_analyze.apply(lambda x: ["Negative Sentiment"] if x.sentiment < NEGATIVE_SENTIMENT_THRESHOLD else [], axis=1)
      5 df_logs_to_analyze["highlight"] = df_logs_to_analyze.apply(lambda x: True if x.sentiment < NEGATIVE_SENTIMENT_THRESHOLD else False, axis=1)

~/.local/lib/python3.8/site-packages/conversation_analytics_toolkit/sentiment_analysis.py in add_sentiment_columns(df_logs_canonical)
     20 def add_sentiment_columns(df_logs_canonical):
     21     df_logs_canonical['sentiment_result']=\
---> 22         [utterance_sentiment_detailed(user_input) for user_input in df_logs_canonical['request_text']]
     23 
     24     df_logs_canonical['sentiment']=df_logs_canonical['sentiment_result'].str[0]

~/.local/lib/python3.8/site-packages/conversation_analytics_toolkit/sentiment_analysis.py in <listcomp>(.0)
     20 def add_sentiment_columns(df_logs_canonical):
     21     df_logs_canonical['sentiment_result']=\
---> 22         [utterance_sentiment_detailed(user_input) for user_input in df_logs_canonical['request_text']]
     23 
     24     df_logs_canonical['sentiment']=df_logs_canonical['sentiment_result'].str[0]

~/.local/lib/python3.8/site-packages/conversation_analytics_toolkit/sentiment_analysis.py in utterance_sentiment_detailed(user_input)
     52 def utterance_sentiment_detailed(user_input):
     53 
---> 54     sentiment = TextBlob(user_input)
     55 
     56     current_blob_polarity=sentiment.sentiment.polarity

~/.local/lib/python3.8/site-packages/textblob/blob.py in __init__(self, text, tokenizer, pos_tagger, np_extractor, analyzer, parser, classifier, clean_html)
    367                 parser=None, classifier=None, clean_html=False):
    368         if not isinstance(text, basestring):
--> 369             raise TypeError('The `text` argument passed to `__init__(text)` '
    370                             'must be a string, not {0}'.format(type(text)))
    371         if clean_html:

TypeError: The `text` argument passed to `__init__(text)` must be a string, not <class 'float'>

**Comment by ayaeli** [comment] 2020-08-17 10:05
Hi @waleyson .  

Sentiment analysis works on text strings.  Based on the exception details above, the data it receives for some reason is of type float and not string.  

Can you share some more details on your data or how to recreate this issue?  
1. Are you using our sample data, or running on your own data?  can you share a sample row of logs_to_analyze?
2. What is the type of the request_text column (`df_logs_to_analyze["request_text"].dtype`).  Should be string denoted by: `dtype('O')`.  If it is numeric, we should understand why...
3. As a workaround you can try to cast to string (`df_logs_to_analyze["request_text"]= df_logs_to_analyze["request_text"].astype(str)`) and see if this fixes the error.

**Comment by waleyson** [comment] 2020-09-18 09:48
Hello @ayaeli ,
thanks for the response
see response below
1. Yes, I am running on my own data: below is the sample rows
````
                                                   request_text  \
0     Whats is my loan limits                                      
1     Balance Enquiries 📒                                          
2     Yes, I have.                                                 
3                                                                  
4     Yes                                                          
...   ...                                                          
4995                                                               
4996  I want my statement of account from July to September 2020   
4997  Yes                                                          
4998  Activate SMS Alert                                           
4999  I need alert also on my Gmail account                        

                                                                                                                                                                                                                           response_text  \
0     []                                                                                                                                                                                                                                   
1     [I'm happy to assist you 😊., Please, can I get some more information from you?]                                                                                                                                                      
2     [<span style="color: teal">I can assist in many ways including:  </span>]                                                                                                                                                                                                                                        
4     [Okay,<br><br> please go ahead with another question]                                                                                                                                                                                
...                                                     ...                                                                                                                                                                                
4995  [Welcome,😊  My name is . I provide instant, automated client support. How can I help you today? , Please tell me if you have an account]                                                                               
4996  [Kindly hold on ☝]             
`````

**Comment by ayaeli** [comment] 2020-09-29 12:29
After some additional checks, we found that this has been caused by the special characters (e.g. smilies, numbers).  The recent PR https://github.com/watson-developer-cloud/assistant-dialog-flow-analysis/pull/21 should fix this issue.

**Comment by ayaeli** [comment] 2020-10-13 08:50
closing this issue as it has been fixed by above PR

**Closed as completed by ayaeli** 2020-10-13 08:50 UTC
